#!/bin/bash

###########################
# AutoNumlock config file #
###########################

# List of USB keyboards to check for.
# You can specify multiple IDs, separated by space.
# To get your keyboard ID, run `autonumlock -l`
devices=('<DEVICE>')

# Refresh interval (seconds)
# Length of sleep between USB device checks
sleeptime=<SLEEP>


#### When keyboard is connected ####

# plug-in event
function on_connect {
  if [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
    if ! numlock_is_on; then
      ydotool key 69:1 69:0
    fi
  else
    numlockx on
  fi
}


# called each poll when connected
function on_connect_poll {
  false
  # something must be here, or bash throws a syntax error...
}


#### When keyboard is missing ####

# disconnect event
function on_disconnect {
  if [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
    if numlock_is_on; then
      ydotool key 69:1 69:0
    fi
  else
    numlockx off
  fi
}


# called each poll when missing
function on_disconnect_poll {
  false
  # ...
}

function numlock_is_on {
  local led
  for led in /sys/class/leds/*::numlock/brightness; do
    if [[ -r "$led" ]] && [[ "$(<"$led")" -gt 0 ]]; then
      return 0
    fi
  done

  return 1
}
